import{a as R,S as q,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&i(p)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const $="50818292-28c953def5feac0614fc2706b",E="https://pixabay.com/api/";async function h(s,t=1){const o=new URLSearchParams({key:$,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}),{data:i}=await R.get(`${E}?${o}`);return i}const m=document.querySelector(".gallery"),g=document.querySelector(".load-more-btn"),y=document.querySelector(".loader"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const t=s.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
               <ul class="info">
<li class="photo-info">👍 <span class="span">${o.likes}</span></li>
<li class="photo-info">👁 <span class="span">${o.views}</span></li>
<li class="photo-info">💬 <span class="span">${o.comments}</span></li>
<li class="photo-info">⬇️ <span class="span">${o.downloads}</span></li>
</ul>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){m.innerHTML=""}function w(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}function v(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const S=document.querySelector(".form"),O=document.querySelector(".load-more-btn"),l=S.elements["search-text"],u=15;let c="",a=1,f=0;S.addEventListener("submit",async s=>{if(s.preventDefault(),c=l.value.trim(),!c){n.warning({title:"Warning",message:"Enter a search term",position:"topRight"}),l.value="";return}a=1,M(),d(),w();try{const t=await h(c,a);if(f=t.totalHits,t.hits.length===0){n.error({title:"Error",message:"No images found for this query",position:"topRight"}),l.select();return}L(t.hits),l.value="",t.hits.length<u||f<=u?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()):v()}catch{n.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{b()}});O.addEventListener("click",async()=>{a+=1,d(),w();try{const s=await h(c,a);L(s.hits);const{height:t}=document.querySelector(".gallery .gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),a*u>=f||s.hits.length<u?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()):v()}catch{n.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
